### PR TITLE
added crow cv/just friends ii output

### PR DESCRIPTION
**Pull request by swbain**
essentially just copied what @tehn did in this commit in awake: https://github.com/tehn/awake/commit/e941cb9c319a1221ad768f8892943cf3eab14887

### CODE REVIEW

**Comment by markwheeler** [comment]
Hi, I'm unable to test this here but looks good. Much appreciated! :)

**Comment by markwheeler** [comment]
@swbain actually one question on this: is it correct that the additional code within the `output` action is not part of the `all_notes_kill()` method? It shouldn't be executed when playback is stopped for example?

**Comment by swbain** [comment]
@markwheeler no problem! i've been really loving using loom with my new just friends module - many thanks for the work you've put into this. i haven't seen any issues so far but if i (or anyone else) come across bugs i'll patch and put up a PR. sometime in the next few days, i'll likely experiment with adding clocking via crow input.

i think moving that code into `all_notes_kill()` would result in some unnecessary method calls -- that code essentially just prepares crow/just friends to receive note events. crow and just friends don't really have the concept of turning a note off, so calling these setup methods outside of the `output` action when the output is changed doesn't seem needed, although it probably wouldn't introduce any noticeable issues.

**Comment by markwheeler** [comment]
Cool makes sense, thanks for the explanation!

Re clocking, you'll notice that Loom is still using the `beat_clock` system – it'd probably make sense to move it over to the newer clock approach to better integrate/sync but it's not something I've looked into.

**Comment by swbain** [comment]
good to know, i'll keep that in mind as i start to dig in.

**Pull request merged**
